# Cấu hình cơ bản
edition = "2021"
use_small_heuristics = "Max"

# Cấu hình format
newline_style = "Unix"
hard_tabs = false
tab_spaces = 2
reorder_imports = true

# Cấu hình độ rộng
max_width = 100
array_width = 80
chain_width = 60

# Cấu hình struct
# struct_field_align_threshold = 20
