services:
  postgres:
    container_name: jd-postgres
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.postgres
    environment:
      - POSTGRES_USER=jayden
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jaydenblog
      - INIT_DB=${INIT_DB:-true}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jayden -d jaydenblog"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    container_name: jd-redis
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
